Booklibrary/urls.py
from django.urls import path,include
from . import views
app_name = "booklib"
urlpatterns = [
    path('', views.dashboard, name="home"),

]

Payment/urls.py
from django.urls import path
from . import views
app_name = "payment"
urlpatterns = [
    path('', views.payment, name="payment"),

]

boolibraryproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Booklibrary.urls')),  
    path('users/', include('users.urls')),  
    path('payment/', include('Payment.urls')),  
]

users/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('addtocart/', views.addtocart, name="addtocart"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('contact/', views.contact, name="contact"),  
    path('forgottenpassword/', views.forgottenpassword, name="forgottenpassword"),  
    path('bookdetailspage/', views.bookdetailspage, name="bookdetailspage"),  
    ]

Booklibrary/models.py
from django.db import models
from users.models import CustomUser
from . import validators

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='books')
    description = models.TextField(max_length=500)
    published_date = models.DateField()
    language = models.CharField(max_length=255)
    book_price = models.DecimalField(max_digits=10, decimal_places=2)
    cover_image = models.ImageField(upload_to='book_cover/', null=True, blank=True)
    year = models.PositiveIntegerField()
    document = models.FileField(upload_to='books/', null=True, blank=True, validators = [validators.validateDocumentPageLimit])
    # sub_category = models.CharField(max_length=255)

    def __str__(self):
        return self.title

Payment/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class CustomUser(AbstractUser):
    is_author = models.BooleanField(default=False)#when it's clicked (it set to true )
    email = models.EmailField(unique=True)

    USERNAME_FIELD = "email" #email as a unique identify for authentication

    REQUIRED_FIELDS = ["is_author"]
    
    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from . import models

class CustomUserRegistrationForm(UserCreationForm):
    is_author = forms.BooleanField(required=False, label="are you an author?")
    class Meta:
        model = models.CustomUser
        fields = ("email", "is_author", "password1","password2", "username", "first_name", "last_name")


    
class CustomUserLoginForm(AuthenticationForm):
    username = forms.EmailField()

Booklibrary/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request, 'dashboard.html')

Payment/views.py
from django.shortcuts import render

# Create your views here.
def payment(request):
    pass

users/views.py
from django.shortcuts import render
from . import forms

def register(request):
    form = forms.CustomUserRegistrationForm()
    context = {
        "forms" : form
    }
    return render(request, 'register.html', context)

def login(request):
    form = forms.CustomUserLoginForm()
    context = {
        "forms" : form
    }
    return render(request, 'login.html', context)

def addtocart(request):
    return render(request, 'addtocart.html')

def dashboard(request):
    return render(request, 'dashboard.html')

def contact(request):
    return render(request, 'contact.html') 

def bookdetailspage(request):
    return render(request, 'bookdetailspage.html') 

def forgottenpassword(request):
    return render(request, 'forgottenpassword.html')

templates/bookcount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/bookdetailspage.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="./bookdetailspagestyle.css">
    <link rel="stylesheet" href="{% static 'bookdetailspagestyle.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Book description page</title>
</head>
<body>
    <header>
        <img
            src="{% static 'imagefolder/booklogo.png' %}"
            height="35"
            alt=""
            loading="lazy"
          />
        <ul>
            <li><a href="{% url 'user:dashboard' %}">Home</a></li>
            <ul class="menubar">
                <select name="" id="">
                    <option value="">Book Type</option>
                    <option value="entertainment">Entertainment</option>
                    <option value="education">Education</option>
                    <option value="selfhelp">self-help</option>
                    <option value="romance">Romance</option>
                    <option value="horror">Horror</option>
                    <option value="history">History</option>
                    <option value="travel">Travel</option>
                    <option value="health">Health</option>
                    <option value="business">Business</option>
                    <option value="mystery">Mystery</option> 

                </select>
                <li><a href="#">Download App</a></li>
            </ul>
            <li><a href="#">Blog</a></li>
            <li><a href="#"><i class="fa-solid fa-cart-shopping"></i></a></li>
            <li><a href="{% url 'user:register' %}">Registraton</a></li>
        </ul>
    </header>
    <div class="container">
        <section class="bookdescriptionsection">
            <div class="bookCard authorProfilePicture">
                <img src="{% static 'imagefolder/image/5912a6c6fb36fb7c1077ad0c76d3a66d.jpg' %}" alt="">
            </div>
        </section>
        <section class="bookdetailpage">
            <div class="bookdetailsparent">
                <div><h3>You are dead: Detective Superintendent Roy Grace is called to investigate, and soon discovers a connection between Logan's case and the remains of a woman found at a construction site, who has been dead for thirty years.</h3></div>
                <div>
                    <div class="authorprofile">
                        <img class="profile-icon" src="./imagefolder/image/bookdescriptionprofile.jpg" alt="">
                        
                        <p>Peter James</p>
                        <p class="numberofrate">75</p>
                    </div>
                    <div class="starrating">
                        <p><i class="fa-regular fa-star checked"></i>
                            <i class="fa-regular fa-star checked"></i>
                            <i class="fa-regular fa-star checked"></i>
                            <i class="fa-regular fa-star checked"></i>
                            <i class="fa-regular fa-star"></i>
                        </p>
                    </div>
                    <div>You Are Dead by Peter James follows Detective Superintendent Roy Grace as he investigates the abduction of a young woman and uncovers a chilling connection to past murders, revealing the presence of a serial killer in Brighton. The story intensifies with multiple perspectives and unexpected twists, exploring themes of loyalty and fear <a href="">read more</a>.<p>
                        
                    </p></div>
                </div>
                <div class="bookdescription">
                    <div class="tablehead">
                        <H5>PUBLISHER</H5>
                        <H5>YEAR PUBLISHED</H5>
                        <H5>LANGUAGE</H5>
                        <H5>PAGES</H5>
                    </div>
                    <div class="tablevalue">
                        <P>thosmas Nelson Inc</P>
                        <P>December 30th 2014</P>
                        <P>English</P>
                        <P>247p</P>
                    </div>
                </div>
                <div class="edition">
                    <p>Edition</p>
                    <div class="editionbtncontainer">
                        <button class="btnedition" id="active">Kindle</button>
                        <button class="btnedition">Paperback</button>
                        <button class="btnedition">Hard cover</button>
                        <button class="btnedition">Audio</button>
                        
                    </div>
                </div>
                <div class="addtocartcontainer">
                    <div>
                    <button class="addtocart">Add to cart</button>
                    <button class="buynow">Preview item</button>
                 </div>
                </div>
            </div>
        </section>
    </div>
    <section class="relatedbookssection">
        <div class="relatedbooks">
            <h3>Related Books</h3>
            <div class="relatedbookcards">
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/book1.jpeg" alt="Book 1">
                    <h3>Book Title 1</h3>
                    <p>Author Name</p>
                </div>
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/OIP.jpeg" alt="Book 2">
                    <h3>Book Title 2</h3>
                    <p>Author Name</p>
                </div>
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/R.jpeg" alt="Book 3">
                    <h3>Book Title 3</h3>
                    <p>Author Name</p>
                </div>
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/book3.jpeg" alt="Book 3">
                    <h3>Book Title 3</h3>
                    <p>Author Name</p>
                </div>
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/book3.jpeg" alt="Book 3">
                    <h3>Book Title 3</h3>
                    <p>Author Name</p>
                </div>
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/book3.jpeg" alt="Book 3">
                    <h3>Book Title 3</h3>
                    <p>Author Name</p>
                </div>
                <div class="card">
                    <img src="./imagefolder/image/relatedbooks/book3.jpeg" alt="Book 3">
                    <h3>Book Title 3</h3>
                    <p>Author Name</p>
                </div>
            </div>
                
                
                

    </section>
    <footer class="dashboard-footer">
        <div class="footer-content">
            <div class="footer-logo">
                <img src="./imagefolder/booklogo.png" alt="Logo">
                <p>Trusted by thousands of companies around the world.</p>
            </div>
            <div class="footer-links">
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="./dashboard.html">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Support</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <div class="accountsection">
                        <a href="./login.html"><button class="login">Login</button></a>
                        <a href="./login.html"><button class="signup">Start for Free</button></a>
                    </div>
                </ul>
            </div>
            <div class="footer-socials">
                <h3>Follow Us</h3>
                <a href="https://www.facebook.com"><i class="fa-brands fa-facebook"></i></a>
                <a href="https://www.linkedin.com"><i class="fa-brands fa-linkedin"></i></a>
                <a href="https://www.instagram.com"><i class="fa-brands fa-instagram"></i></a>
                <a href="https://www.pinterest.com"><i class="fa-brands fa-pinterest"></i></a>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; 2023 Your Company Name. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="login.css">
    <title>Contact Page</title>
</head>
<body>
    <div id="login-page">
        <header>
        <h1><img src="{% static 'imagefolder/booklogo.png' %}" alt=""></h1>
        <nav>
            <ul>
                <li><a href="{% url 'user:dashboard' %}">Home</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="{% url 'user:contact' %}">Contact</a></li>
                <li><a href="{% url 'user:login' %}" id="login">Login</a></li>
            </ul>
            <div class="searchbar">
                <input type="search" placeholder="Search your favourite book here">
            </div>
        </nav>
    </header>
    <main class="login">
        <div class="login-section">
            <div class="container" id="login-container">
                
                
            </div>
    
            <div class="container" id="register-container" style="display: none;">
                <h2>Register</h2>
                <form id="registerform">
                    <input type="text" placeholder="First Name" required>
                    <input type="text" placeholder="Last Name" required>
                    <input type="email" placeholder="Enter Email" required>
                    <input type="email" placeholder="Confirm Email" required>
                    <input type="password" placeholder="Enter Password" required>
                    <input type="password" placeholder="Confirm Password" required>
                    <button type="submit" id="register-btn">Submit</button>
                    <div class="spinner" id="register-spinner"></div>
                    <p>Already have an account? <a href="{% url 'user:login' %}" id="toggle-login">Login</a></p>
                </form>
            </div>
        </div>
        <div class="scrollingtext">
            <marquee behavior="" direction="">
                <div>
                    <img src="{% static 'imagefolder/loginbackground.jpg' %}" alt="">
                </div>
                <div>
                    <img src="{% static 'imagefolder/loginbackground.jpg' %}" alt="">
                </div>
                <div>
                    <img src="{% static 'imagefolder/loginbackground.jpg' %}" alt="">
                </div>
            </marquee>
        </div>
    </main>
    <footer>
        <p>follow us on</p>
    </footer>
</div>
    <script src="script.js"></script>
</body>
</html>

templates/forgottenpassword.html
<!DOCTYPE html>

<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}Book library project{% endblock %}</title>
</head>
<body>
    <header class="headsection">
        <h2 class="logo"><img src="{% static 'imagefolder/booklogo.png' %}" alt=""></h2>
        <div class="hamburger">
            <div></div>
            <div></div>
            <div></div>
          </div>
        <nav>
            <ul class="menubar">
                <select name="" id="">
                    <option value="">Book Type</option>
                    <option value="entertainment">Entertainment</option>
                    <option value="education">Education</option>
                    <option value="selfhelp">self-help</option>
                    <option value="romance">Romance</option>
                    <option value="horror">Horror</option>
                    <option value="history">History</option>
                    <option value="travel">Travel</option>
                    <option value="health">Health</option>
                    <option value="business">Business</option>
                    <option value="mystery">Mystery</option> 

                </select>
                <li><a href="#">Recommendations</a></li>
                <li><a href="#">Popular</a></li>
                <li><a href="{% url 'user:addtocart' %}"><i class="fa-solid fa-cart-shopping"></i></a></li>
                <li><a href="#">Download App</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">About</a></li>

            </ul>
        </nav>
        <div class="activeprofilesection">
            <div class="accountsection">
                <a href="{% url 'user:login' %}"><button class="login">Login</button></a>
                <a href="{% url 'user:register'%}"><button class="signup">Start for Free</button></a>
            </div>
            <div class="profile" sty>
                <img src="{% static 'imagefolder/IMG_5452.jpg' %}" alt="" height="40"  style="border-radius: 100px;">
            </div>
        </div>
    </header>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}   
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <title>Login Page</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div id="login-page" class="container-fluid">
        <header>
            <h1><img src="{% static 'imagefolder/booklogo.png' %}" alt=""></h1>
            <nav>
                <ul>
                    <li><a href="{% url 'user:dashboard' %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="{% url 'user:contact' %}">Contact</a></li>
                    <li><a href="{% url 'user:login' %}" id="login">Login</a></li>
                </ul>
                <div class="searchbar">
                    <input type="search" placeholder="Search your favourite book here">
                </div>
            </nav>
        </header>
        <form action="">
            {{forms}}
        </form>
        
        <footer class="text-center text-white py-4" style="background-color: rgb(164, 48, 232);">
            <p>Follow us on</p>
            <div class="social mb-3">
                <a href="#" class="px-2"><i class="fab fa-facebook"></i> Facebook</a>
                <a href="#" class="px-2"><i class="fab fa-twitter"></i> Twitter</a>
                <a href="#" class="px-2"><i class="fab fa-instagram"></i> Instagram</a>
                <a href="#" class="px-2"><i class="fab fa-linkedin"></i> LinkedIn</a>
            </div>
            <nav>
                <ul class="list-unstyled">
                    <li class="d-inline mx-2"><a href="{% url 'user:dashboard' %}" class="text-white">Home</a></li>
                    <li class="d-inline mx-2"><a href="#" class="text-white">About</a></li>
                    <li class="d-inline mx-2"><a href="{% url 'user:contact' %}" class="text-white">Contact</a></li>
                    <li class="d-inline mx-2"><a href="{% url 'user:login' %}" class="text-white">Login</a></li>
                </ul>
            </nav>
        </footer>
</div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <title>Login Page</title>
</head>
<body>
    <div id="login-page">
        <header>
        <h1><img src="{% static 'imagefolder/booklogo.png' %}" alt=""></h1>
        <nav>
            <ul>
                <li><a href="{% url 'user:dashboard' %}">Home</a></li>
            <li><a href="about.html">About</a></li>
                <li><a href="./contact.html">Contact</a></li>
                <li><a href="{% url 'user:login' %}" id="login">Login</a></li>
            </ul>
            <div class="searchbar">
                <input type="search" placeholder="Search your favourite book here">
            </div>
        </nav>
    </header>
    <main class="login">
        <div class="login-section">    
                <div class="container" id="register-container">
                    <div>
                        <h2>Register</h2>
                        <form action="" class="register-form">
                            {{forms}}
                        </form>
                    </div>
                
                    <div class="register-text">
                        <h2>
                            <span>WELCOME TO</span><br>
                            <span>OUR</span><br>
                            <span>BOOKSTORE</span>
                        </h2>
                        <p>knowledge is your Decision,Dedication,Despiration <br>
                        you can get everything you wann when you work hard and stick  to the plan</p>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <footer>
        <p>follow us on</p>
    </footer>
</div>
</body>
</html>